"""add intraday_minutes and intraday_ticks tables

Revision ID: 11acbb22d68f
Revises: 7c128434b0a7
Create Date: 2026-03-09 00:23:10.507733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11acbb22d68f'
down_revision: Union[str, None] = '7c128434b0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intraday_minutes',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minute_time', sa.Time(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date', 'minute_time')
    )
    op.create_index('ix_intraday_minutes_stock_date', 'intraday_minutes', ['stock_id', 'date'], unique=False)
    op.create_table('intraday_ticks',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tick_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date', 'tick_time')
    )
    op.create_index('ix_intraday_ticks_stock_date', 'intraday_ticks', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intraday_ticks_stock_date', table_name='intraday_ticks')
    op.drop_table('intraday_ticks')
    op.drop_index('ix_intraday_minutes_stock_date', table_name='intraday_minutes')
    op.drop_table('intraday_minutes')
    # ### end Alembic commands ###
