"""Add margin_trading and broker_trading tables

Revision ID: 994398fcd33e
Revises: cdd052d880d7
Create Date: 2026-03-08 00:52:45.589163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994398fcd33e'
down_revision: Union[str, None] = 'cdd052d880d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_trading',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('broker_id', sa.String(length=10), nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('buy_volume', sa.BigInteger(), nullable=False),
    sa.Column('sell_volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('date', 'stock_id', 'broker_id')
    )
    op.create_index('ix_broker_trading_stock_date', 'broker_trading', ['stock_id', 'date'], unique=False)
    op.create_table('margin_trading',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('margin_buy', sa.BigInteger(), nullable=False),
    sa.Column('margin_sell', sa.BigInteger(), nullable=False),
    sa.Column('margin_cash_repay', sa.BigInteger(), nullable=False),
    sa.Column('margin_balance_prev', sa.BigInteger(), nullable=False),
    sa.Column('margin_balance', sa.BigInteger(), nullable=False),
    sa.Column('margin_limit', sa.BigInteger(), nullable=False),
    sa.Column('short_buy', sa.BigInteger(), nullable=False),
    sa.Column('short_sell', sa.BigInteger(), nullable=False),
    sa.Column('short_cash_repay', sa.BigInteger(), nullable=False),
    sa.Column('short_balance_prev', sa.BigInteger(), nullable=False),
    sa.Column('short_balance', sa.BigInteger(), nullable=False),
    sa.Column('short_limit', sa.BigInteger(), nullable=False),
    sa.Column('offset', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('date', 'stock_id')
    )
    op.create_index('ix_margin_trading_stock_date', 'margin_trading', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_margin_trading_stock_date', table_name='margin_trading')
    op.drop_table('margin_trading')
    op.drop_index('ix_broker_trading_stock_date', table_name='broker_trading')
    op.drop_table('broker_trading')
    # ### end Alembic commands ###
