"""initial schema

Revision ID: cdd052d880d7
Revises: 
Create Date: 2026-03-07 23:34:54.746180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd052d880d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('major_holders',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('holding_level', sa.Integer(), nullable=False),
    sa.Column('holder_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.BigInteger(), nullable=False),
    sa.Column('holding_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('date', 'stock_id', 'holding_level')
    )
    op.create_index('ix_major_holders_stock_date', 'major_holders', ['stock_id', 'date'], unique=False)
    op.create_table('raw_chips',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('foreign_buy', sa.BigInteger(), nullable=False),
    sa.Column('foreign_sell', sa.BigInteger(), nullable=False),
    sa.Column('foreign_net', sa.BigInteger(), nullable=False),
    sa.Column('foreign_dealer_buy', sa.BigInteger(), nullable=False),
    sa.Column('foreign_dealer_sell', sa.BigInteger(), nullable=False),
    sa.Column('foreign_dealer_net', sa.BigInteger(), nullable=False),
    sa.Column('trust_buy', sa.BigInteger(), nullable=False),
    sa.Column('trust_sell', sa.BigInteger(), nullable=False),
    sa.Column('trust_net', sa.BigInteger(), nullable=False),
    sa.Column('dealer_net', sa.BigInteger(), nullable=False),
    sa.Column('dealer_self_buy', sa.BigInteger(), nullable=False),
    sa.Column('dealer_self_sell', sa.BigInteger(), nullable=False),
    sa.Column('dealer_self_net', sa.BigInteger(), nullable=False),
    sa.Column('dealer_hedge_buy', sa.BigInteger(), nullable=False),
    sa.Column('dealer_hedge_sell', sa.BigInteger(), nullable=False),
    sa.Column('dealer_hedge_net', sa.BigInteger(), nullable=False),
    sa.Column('total_net', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('date', 'stock_id')
    )
    op.create_index('ix_raw_chips_stock_date', 'raw_chips', ['stock_id', 'date'], unique=False)
    op.create_table('raw_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('trade_volume', sa.BigInteger(), nullable=False),
    sa.Column('trade_value', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('date', 'stock_id')
    )
    op.create_index('ix_raw_prices_stock_date', 'raw_prices', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_prices_stock_date', table_name='raw_prices')
    op.drop_table('raw_prices')
    op.drop_index('ix_raw_chips_stock_date', table_name='raw_chips')
    op.drop_table('raw_chips')
    op.drop_index('ix_major_holders_stock_date', table_name='major_holders')
    op.drop_table('major_holders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
